drop table if exists ator CASCADE;

drop table if exists ator_filme CASCADE;

drop table if exists avaliacao_critica CASCADE;

drop table if exists critico CASCADE;

drop table if exists diretor CASCADE;

drop table if exists estudio CASCADE;

drop table if exists filme CASCADE;

drop table if exists seriado CASCADE;

create table ator
(
    id           integer generated by default as identity,
    altura       decimal(19, 2),
    aniversario  timestamp,
    biografia    varchar(255),
    naturalidade varchar(255),
    nome         varchar(255),
    primary key (id)
);

create table ator_filme
(
    id_author integer not null,
    id_ator   integer not null
);

create table avaliacao_critica
(
    id        integer generated by default as identity,
    descricao varchar(255),
    nota      integer,
    revista   varchar(255),
    id_filme  integer not null,
    primary key (id)
);

create table critico
(
    id           integer generated by default as identity,
    aniversario  date,
    bibliografia varchar(255),
    nome         varchar(255),
    publicacoes  varchar(255),
    id_avaliacao integer,
    primary key (id)
);

create table diretor
(
    id           integer generated by default as identity,
    aniversario  date,
    naturalidade varchar(255),
    nome         varchar(255),
    primary key (id)
);

create table estudio
(
    id           integer generated by default as identity,
    ano_fundacao integer,
    nome         varchar(255),
    pais         varchar(255),
    presidente   varchar(255),
    primary key (id)
);

create table filme
(
    id             integer generated by default as identity,
    ano_estreia    integer,
    bilheteria     varchar(255),
    classificao    varchar(255),
    duracao        time,
    pais_de_origem varchar(255),
    sinopse        varchar(255),
    titulo         varchar(255),
    id_diretor     integer not null,
    id_estudio     integer not null,
    primary key (id)
);

create table seriado
(
    id             integer generated by default as identity,
    ano_estreia    integer,
    classificao    varchar(255),
    name           varchar(255),
    pais_de_origem varchar(255),
    sinopse        varchar(255),
    temporadas     integer,
    titulo         varchar(255),
    primary key (id)
);

alter table ator_filme
    add constraint FK5f3dcp8o49rl6qx6ae08is44q
        foreign key (id_ator)
            references filme;

alter table ator_filme
    add constraint FKrhknrd553xcfasp3iutff5vb2
        foreign key (id_author)
            references ator;

alter table avaliacao_critica
    add constraint FKs6qadcfhew5dq7dvmh6utm8tm
        foreign key (id_filme)
            references filme;

alter table critico
    add constraint FKqog1lbeo4e0v6gc283ecc4dof
        foreign key (id_avaliacao)
            references avaliacao_critica;

alter table filme
    add constraint FKn72npavhpw3hrd4j6qpuh2ivp
        foreign key (id_diretor)
            references diretor;

alter table filme
    add constraint FKfe5ao5lvhxqoqcmu0e0vu0tvq
        foreign key (id_estudio)
            references estudio;
